name: "Build"
on:
  pull_request:
  push:
    branch: main
jobs:
  build-flake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@V27
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    # TODO for binary cache
    #- name: Setup cachix
    #  uses: cachix/cachix-action@v10
    #  with:
    #    name: <YOUR_NAME>
    #    signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: List flake structure
      run: nix flake show
    # takes too long and is made obsolete by garnix.io:
    # - run: nix flake check -vL
